version: "3.8"

services:
  network_state_db:
    image: mongo:latest
    container_name: otto_network_state_db
    ports:
      - "27017:27017"
    restart: always

  processed_intents_db:
    image: mongo:latest
    container_name: otto_processed_intents_db
    volumes:
      - "/var/lib/otto_processed_intents:/data/db"
    ports:
      - "27018:27017"
    restart: always

  otto_authentication_db:
    image: mysql:latest
    container_name: otto_authentication_db
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=authentication_db
    ports:
      - "3306:3306"
    volumes:
      - "authentication_db:/var/lib/mysql"
    restart: always

volumes:
  authentication_db:
